name: Create Release Tag
on:
  workflow_dispatch:
    inputs:
      tag-message:
        description: 'Tag message'
        required: true
      user-name:
        description: 'Git user name'
        required: true
      user-email:
        description: 'Git user email'
        required: true
      release-title:
        description: 'GitHub release title'
        required: true
      release-description:
        description: 'GitHub release description'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.email "${{ github.event.inputs.user-email }}"
          git config --global user.name "${{ github.event.inputs.user-name }}"
      - name: Get Release Version
        id: get_release_version
        run: |
          echo ::set-output name=version::$(cat release-version)
      - name: Create Tag
        run: |
          git tag -a "${{ steps.get_release_version.outputs.version }}" -m "${{ github.event.inputs.tag-message }}"
          git push origin "${{ steps.get_release_version.outputs.version }}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_release_version.outputs.version }}
          release_name: ${{ github.event.inputs.release-title }}
          body: ${{ github.event.inputs.release-description }}
          draft: false
          prerelease: false
          target_commitish: release
          github_release: 'true'
