name: Create Release Tag
on:
  workflow_dispatch:
    inputs:
      tag-message:
        description: 'Tag message'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release Version
        id: get_release_version
        run: |
          echo ::set-output name=version::$(cat release-version)
      - name: Create Tag
        run: |
          git tag -a "${{ steps.get_release_version.outputs.version }}" -m "${{ github.event.inputs.tag-message }}"
          git push origin "${{ steps.get_release_version.outputs.version }}"
